### ISSUE TITLE
NoClassDefFoundError for MCTransform3d

### ISSUE THREAD

**Issue by shadowfacts** [NOVAAPI/NovaExample#11]
I just tried to start MC through IDEA after cloning the NovaExample repo and running `gradle setupDecompWorkspace idea` (I also used `--daemon` but that shouldn't be relevant).

Edit:
Crash Log: http://pastebin.ubuntu.com/11400359/

**Comment by RX14** [comment]
Does it occur using gradle runClient? If not then it's a configuration error. Workspace setup docs are in progress.

**Comment by shadowfacts** [comment]
Yep, same thing with `runClient`.

**Comment by RX14** [comment]
Can you post the whole log an stack trace?

**Comment by RX14** [comment]
Shit, didn't see it

**Comment by RX14** [comment]
This isn't really my area and I'm currently on my phone in bed so... Wait for @Calclavia?

**Comment by calclavia** [comment]
Pls wait for the docs. This is definitely a wrong set up.

**Comment by RX14** [comment]
gradle runClient should ALWAYS work.
