### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by Kubuxu** [NOVAAPI/NovaExample#8]
As NovaExample can be used as base for other mods it should be published on less limiting license.

I am proposing shift to MIT License. To do that I need permission from all contributors to NovaExample.

List:
- [x] @calclavia 
- [x] @Victorious3 
- [x] @stanhebben 
- [x] @gamemanj 
- [x] @stanhebben 
- [x] @RX14 
- [x] @Kubuxu
- [x] @asiekierka 
- [x] @magik6k
- [x] @Mitchellbrine
- [x] @Vexatos

I request all mentioned above to give permission to MIT license by commenting under this issue with words "I agree". If someone disagree I would like to listen to his reason.

**Comment by RX14** [comment]
I agree

**Comment by magik6k** [comment]
I agree

**Comment by Victorious3** [comment]
I agree

**Comment by asiekierka** [comment]
Just make it CC0 already. But I agree.

**Comment by Kubuxu** [comment]
@asiekierka CC0 is 1st long, 2nd is not software specific and leaves many points about programming.

**Comment by stanhebben** [comment]
Agreed

**Comment by RX14** [comment]
Creative commons licences on code always seem off to me, maybe CC0 is more generic but the CC licences are mostly **not** made for code so lack in various ways. I always wince when I see a minecraft mod CC licenced.

**Comment by skyem123** [comment]
[Well...](https://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F)

**Comment by Mitchellbrine** [comment]
I agree

**Comment by ghost** [comment]
I agree.

**Comment by Vexatos** [comment]
Wait, I did something to this repo? Anyway, you have my permission, of course.

I agree.

:suspect:

**Comment by calclavia** [comment]
I agree

**Comment by Kubuxu** [comment]
Commit by @TheOnlyQueue is only spelling fix in javadoc of a class (3e85dcdf580858f51ea960b01530bacbf68ae6f3) and in my opinion this contribution does not require  permission for re-licensing.

**Comment by Kubuxu** [comment]
Done in 41b44e5080bf6bba623dbb9972eebb641791c87d.
