### ISSUE TITLE
Shouldn't maven repo in build.gradle be "maven.novaapi.net" ?

### ISSUE THREAD

**Issue by halvors** [NOVAAPI/NovaExample#9]
Shouldn't maven repo in build.gradle be "maven.novaapi.net" ? 

Currently it is http://maven.magik6k.net/

**Comment by Kubuxu** [comment]
As RX14 said. Those are the same mavens and when gradle setup was created novaapi.net wasn't yet ours; then nobody cared to change it. As PR got accepted I am closing this.
